name: Debug Pages Build

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print tree
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -name package.json -o -name package-lock.json -o -name dist -type d

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: npm ci
        run: |
          set -euxo pipefail
          npm ci --no-audit --no-fund
          npm -v
          node -v

      - name: Build
        run: |
          set -euxo pipefail
          npm run build
          ls -la dist || true

      - name: Add SPA fallback (ignore if no dist)
        run: |
          if [ -d dist ]; then cp dist/index.html dist/404.html || true; fi

      - name: Upload artifact (fail if dist missing)
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
