name: Deploy UI to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Detect where package.json is
      - name: Detect package directory
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          for d in . agent/ui frontend ui web app client; do
            if [ -f "$d/package.json" ]; then
              echo "pkg_dir=$d" >> "$GITHUB_OUTPUT"
              echo "Detected package dir: $d"
              exit 0
            fi
          done
          echo "❌ No package.json found in ., agent/ui, frontend, ui, web, app, or client"
          exit 1

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ steps.detect.outputs.pkg_dir }}/package-lock.json

      - name: Install deps
        working-directory: ${{ steps.detect.outputs.pkg_dir }}
        run: |
          set -euxo pipefail
          [ -f package-lock.json ] || npm install --package-lock-only
          npm ci --no-audit --no-fund

      - name: Build
        working-directory: ${{ steps.detect.outputs.pkg_dir }}
        run: |
          set -euxo pipefail
          if ! jq -e '.scripts.build' package.json >/dev/null 2>&1; then
            echo "❌ No 'build' script in package.json (add e.g. \"build\": \"vite build\")"
            jq '.scripts' package.json || true
            exit 1
          fi
          npm run build

      - name: Detect build output folder
        id: out
        working-directory: ${{ steps.detect.outputs.pkg_dir }}
        run: |
          set -euo pipefail
          for d in dist build .output/public out; do
            if [ -d "$d" ]; then
              echo "build_dir=${{ steps.detect.outputs.pkg_dir }}/$d" >> "$GITHUB_OUTPUT"
              echo "Detected build dir: $d"
              exit 0
            fi
          done
          echo "❌ No build output folder found (tried: dist, build, .output/public, out)."
          exit 1

      - name: Add SPA fallback (optional)
        run: |
          set -euo pipefail
          if [ -f "${{ steps.out.outputs.build_dir }}/index.html" ]; then
            cp "${{ steps.out.outputs.build_dir }}/index.html" "${{ steps.out.outputs.build_dir }}/404.html" || true
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.out.outputs.build_dir }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
